name: CI - Build, Test and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permitir execução do Gradle
        run: chmod +x ./gradlew

      - name: Rodar testes e gerar cobertura
        run: ./gradlew clean test jacocoTestReport

      - name: Upload do relatório de cobertura (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura-jacoco
          path: build/reports/jacoco/test/html

